spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socialmedia_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type: trace
        jdbc.lob.non_contextual_creation: true
server:
  servlet:
    context-path: /


logging:
  #file: ${spring.application.name}.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-20thread] %5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %-5logger{0} - %msg%n"


